environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_fyOm4E
  projectIdentifier: TestDataSourceRemoteEnvironment_fyOm4E
  identifier: TestDataSourceRemoteEnvironment_fyOm4E
  tags: {}
  name: TestDataSourceRemoteEnvironment_fyOm4E
  type: PreProduction
