pipeline:
  name: remote-pip-1
  identifier: remotepip1
  projectIdentifier: Gitx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: st1
        identifier: st1
        template:
          templateRef: account.st1
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: remoteservice1
            gitBranch: lc-2
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            serviceOverrideInputs: <+input>
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 100m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  name: ssss
                  identifier: ssss
                  template:
                    templateRef: Remotetemp2
                    versionLabel: "1"
                    gitBranch: main
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
